before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w
    main: ./cmd/caddy
    binary: caddy-discord
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-rc"
changelog:
  disable: true
release:
  github:
    owner: enum-gg
    name: caddy-discord
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append
  header: |
    ## {{ .Tag }}
