before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    main: ./cmd/agent
    binary: agent
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-rc"
changelog:
  sort: asc
  skip: false
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  mode: append
  header: |
    ## {{ .Tag }}
