on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: bump-version

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: go
          package-name: caddy-discord
          token: ${{ secrets.NICE_TOKEN }}
